### PR TITLE
Delete customLabel. Fixes #290

### LINKED ISSUE #290: Cannot remove a custom label
Today I set a custom label for a transaction and then noticed I made a mistake.
I wanted to remove it by erasing the text and setting an empty custom label, but that did not work: the application does not allow to set an empty custom label when there is already one (non-empty).

### PR DESCRIPTION
**Pull request by ZeHiro**
[Review on Reviewable](https://reviewable.io/reviews/bnjbvr/kresus/299)

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thank you for the patch! I think we can make it slightly simpler, though...

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/components/OperationList.js, line 190 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K6-h8PCPUiHrxyyR5p1:-K6-h8PCPUiHrxyyR5p2:-2130068474) ([raw file](https://github.com/bnjbvr/kresus/blob/65f7ecc7c9567de443c57a39d14ccde3ac668919/client/components/OperationList.js#L190)):*
Let's make the conditions simpler:

```
if (customLabel && constumLabel !== this.defaultValue()) {
  if (customLabel.trim().length) {
    //etc
  } else if (this.props.operation.customLabel.length) {
    //etc
  }
}
```

---

*[client/components/OperationList.js, line 192 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65PyAfEkZw65aMLpBg:-K65PyAfEkZw65aMLpBh:-1367131508) ([raw file](https://github.com/bnjbvr/kresus/blob/65f7ecc7c9567de443c57a39d14ccde3ac668919/client/components/OperationList.js#L192)):*
Can you, here and below, replace '' by `null`? This would be equivalent to having no customLabel as defined in client/Models.js.
In this case, I think the server wants to check that if the field to update is customLabel and its value is null, we want to erase the property, rather than setting it to null and saving it.

---

*[client/components/OperationList.js, line 194 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65QUaU_5toH-l_bbUR:-K65QUaU_5toH-l_bbUS:-862748159) ([raw file](https://github.com/bnjbvr/kresus/blob/65f7ecc7c9567de443c57a39d14ccde3ac668919/client/components/OperationList.js#L194)):*
Note: trailing spaces at EOL

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-:-K65QP32bax_MJ84UyOq:-1501015596)*

**Comment by ZeHiro** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/components/OperationList.js, line 190 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K6-h8PCPUiHrxyyR5p1:-K65SwaZTrA2OiSOz0GL:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/65f7ecc7c9567de443c57a39d14ccde3ac668919/client/components/OperationList.js#L190)):*
Done.

---

*[client/components/OperationList.js, line 192 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65PyAfEkZw65aMLpBg:-K65RUlWfsWtfvS-cGvp:254584747) ([raw file](https://github.com/bnjbvr/kresus/blob/65f7ecc7c9567de443c57a39d14ccde3ac668919/client/components/OperationList.js#L192)):*
In fact setting it to null, the result is the same on the sent request. But I'll delete the property server side.

---

*[client/components/OperationList.js, line 194 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65QUaU_5toH-l_bbUR:-K65Sy9ALv6hCOldm3Dv:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/65f7ecc7c9567de443c57a39d14ccde3ac668919/client/components/OperationList.js#L194)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/299)*

**Comment by bnjbvr** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/components/OperationList.js, line 181 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65dpJX77Q07QoYs4pk:-K65dpJX77Q07QoYs4pl:1470625545) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/client/components/OperationList.js#L181)):*
nit: rm this

---

*[client/components/OperationList.js, line 188 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65e7UhhPtEiLLEqhd6:-K65e7UhhPtEiLLEqhd7:1080636625) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/client/components/OperationList.js#L188)):*
I think the `else` should go on the inner `if`. Also, might want to check `this.props.operation.customLabel` before testing its `length` attribute, in case it's `null` (sorry i should have seen this in my previous comment).

---

*[server/controllers/operations.js, line 57 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65eS3JfPSEe0MliWbg:-K65eS3JfPSEe0MliWbh:-150375337) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/server/controllers/operations.js#L57)):*
nit: trailing spaces

---

*[server/controllers/operations.js, line 62 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65eXwtloQr3pVtAlcn:-K65eXwulDRVdIJxAmQT:153709221) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/server/controllers/operations.js#L62)):*
As you said on irc, we need to use the `save` method on the instance here, not `updateAttributes`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/299)*

**Comment by ZeHiro** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/components/OperationList.js, line 181 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65dpJX77Q07QoYs4pk:-K65fmiduWGX-KH7WVkc:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/client/components/OperationList.js#L181)):*
Done.

---

*[client/components/OperationList.js, line 188 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65e7UhhPtEiLLEqhd6:-K65fu9rZXx7IASQP_mV:333666044) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/client/components/OperationList.js#L188)):*
The else has to be there. Otherwise, we never delete the customLabel, as testing '' returns false

---

*[server/controllers/operations.js, line 57 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65eS3JfPSEe0MliWbg:-K65gOWDuwoda-CJOolo:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/server/controllers/operations.js#L57)):*
Done.

---

*[server/controllers/operations.js, line 62 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65eXwtloQr3pVtAlcn:-K65gOxhXPgNFW4YIaSv:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/server/controllers/operations.js#L62)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/299)*

**Comment by bnjbvr** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/components/OperationList.js, line 188 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65e7UhhPtEiLLEqhd6:-K65rg7F_SYTfZd89iIS:848587874) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/client/components/OperationList.js#L188)):*
Not sure to understand: we're testing `customLabel.trim().length` here, so its reverse is `!customLabel.trim().length`, which is equivalent to `customLabel.trim().length === 0`, as it's a number. How does that not work?

---

*[server/controllers/operations.js, line 57 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65eS3JfPSEe0MliWbg:-K65rvjPRMEofB9v2rjP:-106939312) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/server/controllers/operations.js#L57)):*
Still seeing them. Is it a bug of Reviewable?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/299)*

**Comment by ZeHiro** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/components/OperationList.js, line 188 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65e7UhhPtEiLLEqhd6:-K67UnYA5IWGMUUw65J3:953568429) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/client/components/OperationList.js#L188)):*
If the customLabel is empty (ie, when deleting it), ```customLabel && customLabel !== this.defaultValue()``` returns false.  It is then necessary to deal with th deletion of the label avter the ```else```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/299)*

**Comment by ZeHiro** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/controllers/operations.js, line 57 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/299#-K65eS3JfPSEe0MliWbg:-K67WglFe-p1KtQsleWQ:612607138) ([raw file](https://github.com/bnjbvr/kresus/blob/cca1002bf22d559a3ad0324632ddf133f4d064fe/server/controllers/operations.js#L57)):*
Forgot one. Done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/299)*

**Comment by bnjbvr** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/299)*

**Comment by ZeHiro** [comment]
@bnjbvr, this seems to be more clean to merge

**Comment by bnjbvr** [comment]
Reviewed 2 of 99 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/299)*

**Comment by bnjbvr** [comment]
Works like a charm, thanks.

**Pull request merged**
