### PR TITLE
retreive iban field from weboob

### PR DESCRIPTION
**Pull request by cylwin**
Hello,

This PR remplace https://github.com/bnjbvr/kresus/pull/164 thank to a comment of @ZeHiro.

Bye.

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thank you for the PR! Please let me know about my comment, and I'll merge it accordingly or wait for your updates.

**Comment by cylwin** [comment]
Hello,
I tried this morning to make this check in the python script, but impossible to make this working.
```python
    def get_balances(self):
        '''
        Grab results returned by connector after activation.

        Issue: connectors are blocking, they should not.
        '''
        results = []
        for account in self.backend.iter_accounts():
            results.append({
                "accountNumber": account.id,
                "label": account.label,
                "balance": unicode(account.balance),
                "iban": unicode(account.iban) == "Not loaded" and None or unicode(account.iban)
            })
            print account.iban
        return results
```

Do you have any idea ?

**Comment by cylwin** [comment]
And for weboob 'Not loaded type' https://github.com/laurentb/weboob/blob/master/weboob/capabilities/base.py#L147

**Comment by bnjbvr** [comment]
What's the error you're seeing? (for the record, you can test the scripts with `python weboob/endpoint.py account BANK_UUID LOGIN PASSWORD`)

Also, to avoid the comment and the string comparison, maybe can you test that `account.iban` is an instance of `NotLoadedType` and put a default value in this case? (Please also add parenthesis to avoid the ambiguity about operators order)

**Comment by cylwin** [comment]
I edited my commit. Is this ok for you ?

**Comment by bnjbvr** [comment]
Yes, that will do it. Thank you!

**Comment by bnjbvr** [comment]
Any plans for showing the IBAN to the user? I could take care of it later, otherwise.

**Comment by cylwin** [comment]
No idea to display the iban to the user.

**Pull request merged**
