### PR TITLE
https://github.com/bnjbvr/kresus/issues/69

### PR DESCRIPTION
**Pull request by ZeHiro**
With only one commit

### CODE REVIEW

**Comment by bnjbvr** [comment]
Perfect, thank you!

**Comment by ZeHiro** [comment]
Not tested.

**Comment by bnjbvr** [comment]
Ha, I assumed you had. Couldn't see any obvious mistakes in the code though, it should be pretty safe... And it looks pretty OK on my instance.

For what it's worth, you can test the incoming branch by:
- uninstalling Kresus, if it was installed.
- go to "choose your apps"
- In the URL field, enter `https://github.com/bnjbvr/kresus.git@incoming`
- here you go!

**Comment by ZeHiro** [comment]
I install a test instance of cozy during the week, and test it then.

**Comment by bnjbvr** [comment]
For what it's worth, a few places were doing the wrong thing: res.status(200); wouldn't return a response, ever. The correct way to do it is res.sendStatus(200). I am not blaming you at all here, as I didn't know either, before I actually looked deeper at Frank's PR :) I've made the necessary fixes on incoming, so no worries.

**Comment by ZeHiro** [comment]
OK Thanks.

**Pull request merged**
