### PR TITLE
Update banks + integration

### PR DESCRIPTION
**Pull request by ZeHiro**
[Review on Reviewable](https://reviewable.io/reviews/bnjbvr/kresus/323)

### CODE REVIEW

**Comment by ZeHiro** [comment]
The last commit needs to be modified because not linted. Will do

**Comment by bnjbvr** [comment]
First pass of comments here. Looks good :) Excited to get support for new banks.

The mapping bank-to-module is a bit unclear sometimes (not your fault, it's weboob that's made this way). For instance, Banque Rhone Alpes is accessible through the Credit Du Nord weboob module. Ideally, we'd have a way to type in the first few letters of the bank and fuzzy-match so as to propose the right module (for instance, if i type `banque rhone alpes` it would propose `credit du nord - banque rhone alpes` as the first solution). Of course, it's much more work and can be done later :)

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[client/components/CustomBankField.js, line 40 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYebyojht7HvPCB4H:-K7YYebyojht7HvPCB4I:1836304636) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/client/components/CustomBankField.js#L40)):*
I'm fine if we'd just remove the placeholder here. There shouldn't be any placeholderKey for new users.

---

*[server/models/bank.js, line 43 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YZ4EI9QFnTQVuczaK:-K7YZ4EI9QFnTQVuczaL:-180742177) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/server/models/bank.js#L43)):*
nit: trailing spaces :p

---

*[server/models/bank.js, line 45 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YZ84K-nB9XMUbHVP3:-K7YZ84K-nB9XMUbHVP4:331164431) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/server/models/bank.js#L45)):*
This is already checked in customFieldsAreEqual and can be removed here.

---

*[shared/banks.json, line 14 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YW3K6s_uoDSfE-IbE:-K7YW3K6s_uoDSfE-IbF:377962418) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L14)):*
Is this really required? It doesn't seem so, on the web site...

---

*[shared/banks.json, line 55 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YWDDEdfBbDio7l812:-K7YWDDEdfBbDio7l813:-921748356) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L55)):*
We don't need to store raw labels anymore, can you please remove all the raw `label`fields when there is a `labelKey`?

---

*[shared/banks.json, line 596 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YXyQ5_Luvr9toBY5s:-K7YXyQ5_Luvr9toBY5t:334693651) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L596)):*
There should be Banque Rhone Alpes in this list as well...

---

*[shared/banks.json, line 806 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYHOtJH5MdIW2YiOj:-K7YYHOtJH5MdIW2YiOk:-153274683) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L806)):*
Is it a mistake that all fields be necessary? That seems unlikely that you need to fill in the secret questions and answers by yourself...

---

*[shared/banks.json, line 866 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYQEOe44hqb59wX0Y:-K7YYQEOe44hqb59wX0Z:472959533) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L866)):*
lol, you know it's vim

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-:-K7YZJd-8M1SO2xvwSFn:1851918446)*

**Comment by ZeHiro** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[client/components/CustomBankField.js, line 40 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYebyojht7HvPCB4H:-K7YkSa1vs177IXthnkz:-1357479498) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/client/components/CustomBankField.js#L40)):*
Placeholders should be kept until there is a proper check and validation of value using weboob regexps

---

*[server/models/bank.js, line 45 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YZ84K-nB9XMUbHVP3:-K7Ykgz58qhqXYFxhXpH:1802939572) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/server/models/bank.js#L45)):*
customFieldAreEqual  does not manage the case where after an upgrade, customFields appear, like with this big bank.json upgrade

---

*[shared/banks.json, line 14 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YW3K6s_uoDSfE-IbE:-K7YjrYKI8sP59laTENA:-2120437675) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L14)):*
Weboob says so, the script just parses this

---

*[shared/banks.json, line 55 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YWDDEdfBbDio7l812:-K7YjveqmSpnYvs0n2Mv:-23059817) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L55)):*
I would use labels in case a new module appears ans we didn  integrate it well. I could help

---

*[shared/banks.json, line 596 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YXyQ5_Luvr9toBY5s:-K7Yk8RbzfYiSuVbnltj:-618606815) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L596)):*
weboob's fault

---

*[shared/banks.json, line 806 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYHOtJH5MdIW2YiOj:-K7YkDLk5h10OL5xJUrf:2049589426) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L806)):*
weboob's fauls as well.

---

*[shared/banks.json, line 866 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYQEOe44hqb59wX0Y:-K7YkIriB87Vy6EGJ9mO:1275517632) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L866)):*
well nano and gedit are not here

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323)*

**Comment by ZeHiro** [comment]
Yes some other are weired also, bu weboob provides wired stuf.

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[server/models/bank.js, line 45 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YZ84K-nB9XMUbHVP3:-K7aVUWZOOlL1BxVnvSA:496632197) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/server/models/bank.js#L45)):*
oups you're right.

---

*[shared/banks.json, line 55 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YWDDEdfBbDio7l812:-K7aX4zp6Ijgj2LYyXxf:-251208624) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L55)):*
It could help

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-:-K7aWpQdCxbZGi6R6kLZ:-741793139)*

**Comment by bnjbvr** [comment]
Thanks for the update. A few more comments below.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/components/CustomBankField.js, line 40 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYebyojht7HvPCB4H:-K7b48JFge_iAIHmMzzh:234709674) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/client/components/CustomBankField.js#L40)):*
OK, but placeholder keys are not saved in the json file, so there is either something missing (the placeholder keys in the JSON file) or something that should be removed (in this line :)).

---

*[server/models/bank.js, line 45 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YZ84K-nB9XMUbHVP3:-K7b4QnFzibtWx-pViRs:-621843459) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/server/models/bank.js#L45)):*
Quoting you: `oups you're right.` Forgot to update your patch here? :)

---

*[server/models/bank.js, line 41 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7b2ON8ssuyb6o0Xd6H:-K7b2ON8ssuyb6o0Xd6I:1691512656) ([raw file](https://github.com/bnjbvr/kresus/blob/fde60adb7cbe7515171564d4f109dcaae8d7bed5/server/models/bank.js#L41)):*
nit: unnecessary parenthesis around the whole condition.

---

*[shared/banks.json, line 55 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YWDDEdfBbDio7l812:-K7b2iplVOBkjSc2WhRh:1359713543) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L55)):*
We could have other automation to do so (e.g. check it during CI, or have a script creating the parse script every night and telling us when a string is missing. I would really like to avoid storing raw, locale-insensitive strings in the database (adding fields is easy, removing them isn't that much).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-:-K7b4k7YJvyWHCPsJe1z:1338240632)*

**Comment by ZeHiro** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/components/CustomBankField.js, line 40 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYebyojht7HvPCB4H:-K7b9zpJasBERf52vCSI:254469843) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/client/components/CustomBankField.js#L40)):*
I forgot to add the placehoder in the bank.json.

---

*[shared/banks.json, line 55 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YWDDEdfBbDio7l812:-K7bAdJ4_HGmuupywqYu:-179716595) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L55)):*
OK. As it is not used, i remove the label of customField, except for the websites selects. When we set an automatic update of banks, we'll have to consider using label for this.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323)*

**Comment by ZeHiro** [comment]
@bnjbvr ready for merge I think

---

Review status: 4 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-:-K7bDKrdNc91WRFJ7LuH:229226714)*

**Comment by bnjbvr** [comment]
Just a few more things...

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/components/CustomBankField.js, line 40 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYebyojht7HvPCB4H:-K7bEyIXo_HilP7Q8Hcl:-1647139120) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/client/components/CustomBankField.js#L40)):*
OK. Can you then reformat the code to look like this?

```
placeholder={
    test
    ? ifTrue
    : ifFalse
}
```

Also, wouldn't it be less weird to store `client.settings.something` in the JSON file, and not have to add `client` here in the translation key?

---

*[shared/banks.json, line 55 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YWDDEdfBbDio7l812:-K7bF_Oy8wmzy56KvUvp:2115701270) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L55)):*
Not sure to understand your last sentence, what do you mean?

---

*[shared/banks.json, line 644 \[r3\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7bEiA0FypX_DYklVWd:-K7bEiA0FypX_DYklVWe:1123723487) ([raw file](https://github.com/bnjbvr/kresus/blob/98b371e532f4cc37615214b25fbffc506a66b5ae/shared/banks.json#L644)):*
No need to store the raw placeholder here, let's use the translations files for this.

---

*[shared/banks.json, line 660 \[r3\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7bEnvrRMyungSEGeYO:-K7bEnvsm_bTJhjZQGUw:-469765787) ([raw file](https://github.com/bnjbvr/kresus/blob/98b371e532f4cc37615214b25fbffc506a66b5ae/shared/banks.json#L660)):*
ditto

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-:-K7bFo0Yv8N8UnZLOIQR:-235033388)*

**Comment by ZeHiro** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/components/CustomBankField.js, line 40 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYebyojht7HvPCB4H:-K7bG-SklO6FMNhOKcNB:-908033292) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/client/components/CustomBankField.js#L40)):*
for the reformatting of the code, the linter says the opposit :p . And for the second, all the keys are without 'client' in the bank.json. I can fix

---

*[shared/banks.json, line 55 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YWDDEdfBbDio7l812:-K7bGPXztoSRdV1PPYDV:1224657378) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L55)):*
In the future, when the bank.json is deleted, and the supported banks are automatically fetched, we should use the label in case there is no translation key.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323)*

**Comment by bnjbvr** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/components/CustomBankField.js, line 40 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYebyojht7HvPCB4H:-K7bJit5i05f1Du6hZ1o:599843229) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/client/components/CustomBankField.js#L40)):*
I am already starting to regret this new linter :-(
OK for the `client` key (it can be done here or later, another PR another commit, as you prefer).

---

*[shared/banks.json, line 55 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YWDDEdfBbDio7l812:-K7bJzvQDhR2k8kFQ1zc:-1983407187) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/shared/banks.json#L55)):*
Thanks for the explanation.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323)*

**Comment by ZeHiro** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/components/CustomBankField.js, line 40 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7YYebyojht7HvPCB4H:-K7bMgsaEiL4Kqf9HIU9:677588487) ([raw file](https://github.com/bnjbvr/kresus/blob/bc2cf91f17751183d90f898c75c520d3e335bf04/client/components/CustomBankField.js#L40)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323)*

**Comment by bnjbvr** [comment]
Reviewed 1 of 2 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323)*

**Comment by bnjbvr** [comment]
Two more small things, please:
- can you delete the existing `placeholder` values? (not the keys)
- can you use snake_case for the placeholderKey names? e.g. `secret_placeholder` instead of `secretPlaceholder` (don't forget to update the locales files as well)

**Comment by bnjbvr** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323)*

**Comment by bnjbvr** [comment]
As stated on IRC, the condition used to trigger updates of Bank is wrong (wells fargo doesn't get an update), if the former bank had no customFields, and the name customFieldsAreEqual is misleading.

Two ways to fix this:
- either trigger the update all the time. A bit more expensive but we'll be sure to have the right values.
- fix the condition: update should trigger if `found` has no customFields and `newBank` has some; or both have them, but they're different (no need to test `typeof`).

By the way, can you remove the TODO above this code, please?

**Comment by bnjbvr** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/models/bank.js, line 42 \[r7\]](https://reviewable.io:443/reviews/bnjbvr/kresus/323#-K7mFiIHjfnAloi7O-Ui:-K7mFiIIBuyy4aTuGxyb:-1736853694) ([raw file](https://github.com/bnjbvr/kresus/blob/08b53b008cca5083a4171be392d60a54c4b9f7c6/server/models/bank.js#L42)):*
no need to put `found.customFields` in this part of the condition: it will trigger if and only if `type of found.customFields !== 'undefined'`, which is an equivalent check.

Remember your Bool laws: `A || (!A && B)` <=> `A || B`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323)*

**Comment by bnjbvr** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323)*

**Comment by bnjbvr** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/323)*

**Comment by bnjbvr** [comment]
Great, thank you!

**Pull request merged**
