### PR TITLE
Added "GAN Assurances" and "Groupama"

### PR DESCRIPTION
**Pull request by ZeHiro**

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thanks for the PR! Considering these two companies are "assurances" companies, do you know which kind of information shall be shown?

**Comment by ZeHiro** [comment]
Well they seem to hanve also banking accounts (Groupama's one is for Epargne Salariale). GAN seems also to have  saving accounts (Epargne logement, livret A, LDD, PEL...) They should be treated as banks for that no?
As I think of it, weboob makes defines diffrent types of bank accounts : 

TYPE_CARD     Card account
TYPE_CHECKING    Transaction, everyday transactions
TYPE_DEPOSIT     Term of Fixed Deposit, has time/amount constraints
TYPE_JOINT     Joint account
TYPE_LOAN     Loan account
TYPE_MARKET     Stock market or other variable investments

Maybe this could be a additional information to add inside the db, there could be a filter over account types.

TYPE_SAVINGS

    Savings/Deposit, can be used for every banking

**Comment by jankeromnes** [comment]
Yes, insurance account are often used as bank accounts as well, e.g. the Plan Assurance Vie in most banks (Credit Mutuel lists it under "assurances" instead of "comptes", but it's used as a savings account with interests, and can also be partly diversified into various company shares).

**Comment by bnjbvr** [comment]
Thanks for the explanation! Sounds good to me.

**Pull request merged**
