### PR TITLE
Revamping of the user interface

### PR DESCRIPTION
**Pull request by AwYiss**
Proposal for a revamping of the user interface (much cleaner than the first PR).

screenshot

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thank you for this PR! The design looks really clean. I have to trust your CSS, but what I'm seeing impresses me.

A few comments on the code that I've made directly on the separate commits (also thank you for that, the splitting is really nice and helped me to review your changes a lot). Are you willing to address them? If not, I can merge your PR and take care of them myself later. Cheers!

**Comment by bnjbvr** [comment]
Thank you for the changes @AwYiss ! Is there anything else you wanted to change, or should I merge your PR now?

**Comment by bnjbvr** [comment]
(I am asking because maybe you wanted to have a look at the brand new Emails section, which might need some changes as well?)

**Comment by AwYiss** [comment]
I noticed some display issues on mobile. Fixing them right now.

**Comment by AwYiss** [comment]
reports-mobile

settings-desktop

settings-mobile

**Comment by ZeHiro** [comment]
Nice :+1: 
What about the menu in mobile mode? Will it be easier to handle?

**Comment by AwYiss** [comment]
FYI, the last commit fixes the following issues in mobile display:
- wells not stacking ;
- title in the mobile navbar having different font and size than the title in the desktop navbar
- list of operations overflowing ;
- menu and content not stacking in the settings section ;
- menu not responsive in the settings section.

I also changed the email section icons to stay in line with my recent changes.

**Comment by AwYiss** [comment]
@ZeHiro : which menu are you refering to?

**Comment by ZeHiro** [comment]
@AwYiss 
In mobile mode, the main menu (left side in desktop mode) is hidden behind a burger icon. In the current version, switching between accounts or "pages" is quite hard (don't no why, but it seems the "clickable zone" is small)

**Comment by AwYiss** [comment]
Well I did some testing on my side and the mobile menu seems to be working fine (I didn't compare with the pre-revamped UI, though).

**Comment by ZeHiro** [comment]
Nice then. :)

**Comment by bnjbvr** [comment]
Thank you @AwYiss. I need to test on my mobile and then I'll merge it. If you're willing to address the two aria-label nits and squash together your last two commits, that'd be great ;)

**Comment by bnjbvr** [comment]
Wow, you manage to fix #103, it seems! Cheers

**Comment by bnjbvr** [comment]
Looks great! Thank you for sticking, and don't hesitate to send other PR like this, or even smaller ones ;)

That being said, I think I am going to split the frontend files into several smaller ones, as they tend to get a big fat, these days.

**Comment by AwYiss** [comment]
I set up a Trello board to keep track of all the small UI issues/improvements that didn't make it in this PR : https://trello.com/b/KlNwlofs (work in progress).

**Pull request merged**
