### PR TITLE
Improve English locale.

### PR DESCRIPTION
**Pull request by jankeromnes**
Also changed `by category by month` to `by category (monthly)`, and `par catégorie par mois` to `par catégorie (mensuel)`, because multiple dimensions are confusing.

### CODE REVIEW

**Comment by jankeromnes** [comment]
P.S. I also switched the `h3.sidebar-bank-header` localized key from `'Banks'` to `'Accounts'`, because the section below arguably contains only bank accounts (web access accounts to banks, and actual currency accounts in banks).

**Comment by jankeromnes** [comment]
P.P.S. Bonus CSS margin quickfix (the space between header and app content was 5px too small).

**Comment by jankeromnes** [comment]
@bnjbvr : le friendly ping.

**Comment by bnjbvr** [comment]
Thanks for the PR! I'll merge it as soon as comments are addressed.

**Comment by jankeromnes** [comment]
Comments addressed, although I used the verb "set up" instead of "set".

**Comment by bnjbvr** [comment]
Thanks! Getting closer, but there is still one typo, so I've taken advantage of this review round to add a few more comments, and this will be merged afterwards!

**Comment by jankeromnes** [comment]
Round 3. Fight!

**Comment by jankeromnes** [comment]
Used "Are you sure about this?" consistently instead of "Are you sure you want to do this?".

Also removed a stray period after the comment `// When installing dependencies`.

**Comment by bnjbvr** [comment]
LGTM, thanks!

**Comment by jankeromnes** [comment]
\o/

**Pull request merged**
