### PR TITLE
Set operation type

### PR DESCRIPTION
**Pull request by ZeHiro**

### CODE REVIEW

**Comment by bnjbvr** [comment]
Hi @ZeHiro, thank you for this PR! Please drop a line when it's ready, I see you've closed and opened it a few times already :)

**Comment by ZeHiro** [comment]
It is ;) I had some problems to fetch and merge your incoming branch.

**Comment by bnjbvr** [comment]
Good to know. Can you squash your commits, please? A merge commit doesn't provide much value in the repository history and it'll be easier for reviewing your changes :)

**Comment by ZeHiro** [comment]
I think my rebase was a bit bourrin. Tel me it this is good to you. If not, I'll revamp it tonight.

**Comment by bnjbvr** [comment]
A bit bourrin, indeed :D
Unfortunately, this doesn't fix the conflicts and instead introduces new ones that need to be solved by hand. Do you mind just rebasing your commit over the changes I've made, please? Sorry to inflict that to you...

**Pull request closed without merging**
