### PR TITLE
First improvement of type/category selection

### PR DESCRIPTION
**Pull request by ZeHiro**

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thanks for the detailed view bits (I think this can be put into the other pull request, maybe in a separate commit).

However, the UX for changing a category / type feels weird to me:

- In a previous commit, I've switched from labels to buttons, to make it more explicit that it can be changed. Some people asked me how one could change categories, so that seems useful for first time users. With this change, one cannot tell anymore that they can change it.
- When I hover on a category type, the line's height change and the position of the label changes (from left-aligned to center-aligned), which feels a bit wonky.
- I'd expect to be able to click on the entire category cell for changing the associated category, which I can't do anymore.

So sorry, while I appreciate the effort, I don't see need for a change here. Is there something wrong with having buttons here?

**Comment by ZeHiro** [comment]
Hi, i totally agree with your comments(change in height, centered/not centered). In fact, i just don't like when the button are always displayed as most of the time they are not necessary. They sould be useful once per operation. Maybe a trick with a css class with a transparent background+no border on mouse out would do the trick. I'll propose a new thing.

**Comment by ZeHiro** [comment]
@bnjbvr , I have modified this a bit. How do you feel with this? The buttons are less visible, and there is no more change of height.

**Comment by bnjbvr** [comment]
I like it better, thanks! However, it feels weird to change only the className of the button in JavaScript: you can simply use the `:hover` CSS property for that matter. Can you switch back to using a 2-states component, instead (that is, remove the `mouseIsOver` and get back to the boolean `editMode`), and just change the CSS, please?

**Comment by ZeHiro** [comment]
OK. I'll do this

**Pull request closed without merging**
