### PR TITLE
Improve the readme

### PR DESCRIPTION
**Pull request by ametaireau**
While reading the readme, I was looking for information that weren't there. Now they are.

### CODE REVIEW

**Comment by bnjbvr** [comment]
Lovely, thank you for the pull request! Mind addressing the two review comments, please? Otherwise I'll take care of it :)

**Comment by ametaireau** [comment]
(updated)

**Comment by bnjbvr** [comment]
Awesome, thank you, you rock!

**Comment by bnjbvr** [comment]
Hmmm, I didn't see that your PR was based on `master`, I usually use `incoming` for unstable versions, which already has modifications for the README as well. My bad for not initially spotting it. I'll merge anyway.

**Comment by ametaireau** [comment]
Oh, then this should be specified in the readme as well ;)

**Pull request merged**
