### PR TITLE
Allow to update weboob without bank accounts

### LINKED ISSUE #280: Add a way to update weboob even with no account set
These last few days, there was a problem with Weboob preventing it to access to my bank account's data. Not knowing this at first, I installed Kresus to try it out on my self-hosted Cozy.
In the meantime, I realized the problem with Weboob on another instance I have. So I decided not to touch anything and configure Kresus on my self-hosted one once everything is back to normal.
The issue between Weboob and my bank is now solved in the latest Weboob update. On my other instance, I just updated it via the appropriate menu, and everything worked again.
When I went to do the same on my self-hosted Cozy, I stumbled upon another issue: Because I don't had any bank account configured on this one, I just can't reach the "Update Weboob" button. I think there should be some way to update it in this case.

### PR DESCRIPTION
**Pull request by nicofrand**
Fixes #280

capture d ecran 2016-01-03 a 17 15 44

[Review on Reviewable](https://reviewable.io/reviews/bnjbvr/kresus/318)

### CODE REVIEW

**Comment by bnjbvr** [comment]
Hi @nicofrand ! Thank you for the PR. It seems that there are some merge conflicts, as shown by travis (previous build was broken, i relaunched one and it found some issues).

Also, about the UX, from looking at the screenshot: Could it be possible to only have one single panel, maybe with 2 tabs? First tab would be selected by default and would contain the "configure a new bank access" section; the other one would be called "advanced" and would show the button to update / reinstall weboob. What do you think?

**Comment by nicofrand** [comment]
Yep I had several issues. At the moment everything is clean on my computer
whereas Github shows merge conflicts.

OK for the tabs.

Le ven. 8 janv. 2016 23:25, Benjamin Bouvier <notifications@github.com> a
écrit :

**Comment by bnjbvr** [comment]
Code looks good, I'd like an update to the UI, maybe a new tab for the ImportModule, if you agree.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/components/MainAccountWizard.js, line 8 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7kY-NFam6oxpcX-Iw-:-K7kY-NFam6oxpcX-Iw0:-121079890) ([raw file](https://github.com/bnjbvr/kresus/blob/8f425a4f522115d39667c02ec6a4e1ba19477de5/client/components/MainAccountWizard.js#L8)):*
nit: no need for a constructor if you're just calling super within it

---

*[client/components/MainAccountWizard.js, line 20 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7kYGYO2uw2EhZqRHRZ:-K7kYGYO2uw2EhZqRHR_:442795409) ([raw file](https://github.com/bnjbvr/kresus/blob/8f425a4f522115d39667c02ec6a4e1ba19477de5/client/components/MainAccountWizard.js#L20)):*
Can you put one tag per line, aligning the start one with the end one, please?

---

*[client/components/MainAccountWizard.js, line 24 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7kZU4y9U95eO3pVeW7:-K7kZEDxNpBAIQfqpPZD:-418602942) ([raw file](https://github.com/bnjbvr/kresus/blob/8f425a4f522115d39667c02ec6a4e1ba19477de5/client/components/MainAccountWizard.js#L24)):*
I am not a big fan of what it looks like. Maybe we could color the background as well? It's a bit weird to have the tab's background as one color, a line with no color and then the  new bank panel with grey background.

Also, how about putting the Import module in another tab, now that we have tabs? It's almost free :-)

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-:-K7kYlsPAga03vnR3wNM:-240797019)*

**Comment by nicofrand** [comment]
Review status: 2 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[client/components/MainAccountWizard.js, line 8 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7kY-NFam6oxpcX-Iw-:-K7m8cSJH3hi0O3vZuZ4:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/fc97467a0cf7b95ec5b7bbee915c529571dbd700/client/components/MainAccountWizard.js#L8)):*
Done.

---

*[client/components/MainAccountWizard.js, line 20 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7kYGYO2uw2EhZqRHRZ:-K7m8_xwFqM1XusU1h1G:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/fc97467a0cf7b95ec5b7bbee915c529571dbd700/client/components/MainAccountWizard.js#L20)):*
Done.

---

*[client/components/MainAccountWizard.js, line 24 \[r1\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7kZU4y9U95eO3pVeW7:-K7m8gA43zqYQZJTUSLP:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/fc97467a0cf7b95ec5b7bbee915c529571dbd700/client/components/MainAccountWizard.js#L24)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/318)*

**Comment by bnjbvr** [comment]
Thank you for the update! The new design looks better.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/components/MainAccountWizard.js, line 12 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7mCPsZIGuUibnmRkjg:-K7mCPs_dLECUstMEu6a:1116173588) ([raw file](https://github.com/bnjbvr/kresus/blob/791730eff036d0c8ec4c5c3ae3930408596db782/client/components/MainAccountWizard.js#L12)):*
The h1 should have the class `panel-title` and be wrapped inside a `div` with the class `panel-heading`, instead. Hopefully, that should fix the fact that the title is really too big.

---

*[client/components/MainAccountWizard.js, line 38 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7mCjKgC1cJifxRA2GM:-K7mCjKgC1cJifxRA2GN:-1638988928) ([raw file](https://github.com/bnjbvr/kresus/blob/791730eff036d0c8ec4c5c3ae3930408596db782/client/components/MainAccountWizard.js#L38)):*
How about hoisting this paragraph out of the tab, so that one can read it even if you're not in the right tab? (The `ul` above would be a sibling)

---

*[shared/locales/en.js, line 10 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7mBG2KAmxue933uwCA:-K7mBG2KAmxue933uwCB:-826852854) ([raw file](https://github.com/bnjbvr/kresus/blob/791730eff036d0c8ec4c5c3ae3930408596db782/shared/locales/en.js#L10)):*
Please use snake_case for translation keys (don't forget to replace the use and the key in the fr.js file as well)

---

*[shared/locales/en.js, line 23 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7mBBm1UVkfMk0Wbv8r:-K7mBBm1UVkfMk0Wbv8s:1814462945) ([raw file](https://github.com/bnjbvr/kresus/blob/791730eff036d0c8ec4c5c3ae3930408596db782/shared/locales/en.js#L23)):*
This belongs to another commit/PR

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-:-K7mC2naar71un7iEXg6:708543753)*

**Comment by nicofrand** [comment]
Review status: 2 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/components/MainAccountWizard.js, line 12 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7mCPsZIGuUibnmRkjg:-K7ocVKTeyvnR1MGIRRv:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/791730eff036d0c8ec4c5c3ae3930408596db782/client/components/MainAccountWizard.js#L12)):*
Done.

---

*[client/components/MainAccountWizard.js, line 38 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7mCjKgC1cJifxRA2GM:-K7ocWRAX9ojYJDSDnrk:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/791730eff036d0c8ec4c5c3ae3930408596db782/client/components/MainAccountWizard.js#L38)):*
Done.

---

*[shared/locales/en.js, line 10 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7mBG2KAmxue933uwCA:-K7ocXf4QEfmvHMNd4_V:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/791730eff036d0c8ec4c5c3ae3930408596db782/shared/locales/en.js#L10)):*
Done.

---

*[shared/locales/en.js, line 23 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/318#-K7mBBm1UVkfMk0Wbv8r:-K7ocXM0VG5tGxmveqzt:-499146009) ([raw file](https://github.com/bnjbvr/kresus/blob/791730eff036d0c8ec4c5c3ae3930408596db782/shared/locales/en.js#L23)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/318)*

**Comment by bnjbvr** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/318)*

**Comment by bnjbvr** [comment]
Thank you, looks nice. Can you rebase, please?

**Comment by bnjbvr** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/318)*

**Comment by bnjbvr** [comment]
As I've locally rebased, github didn't detect this was merged. Thanks for the PR as usual :) https://github.com/bnjbvr/kresus/commit/d4c25235b62a8f22ca3598808630e69e5a960941

**Pull request closed without merging**
