### PR TITLE
Added a check for Python's binary

### PR DESCRIPTION
**Pull request by babolivier**
Check for `python`, then for `python2`, then abort if none of them found.

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thank you for the PR! Any way we could have a script that wraps the python binary, to avoid code duplication?

**Comment by babolivier** [comment]
Dunno, I'll try a few things during the day.

**Comment by bnjbvr** [comment]
Closing this PR: the code has so much changed that this isn't viable in the `incoming` branch. Thank you for opening a PR though, and feel free to contribute again whenever you want to <3

**Comment by babolivier** [comment]
Yep, no time to work on this :(

Such awesome, much app, very love, wow <3

**Pull request closed without merging**
