### PR TITLE
Deleting the last account of a bank, deletes the bank client side.

### LINKED ISSUE #306: On deletion of the last account of a bank, the bank is still displayed on the client
Go to settings
Delete the last account of a bank

What is expected: 
- the bank is not shown anymore on the client

What I see: 
- the bank is still displayed.

On reload of the app, the bank is not displayed anymore.

Also, a request "GET /accounts/accountID" is thrown just after the deletion. (accountID being the data-system ID of the deleted account)

### PR DESCRIPTION
**Pull request by ZeHiro**
Fixes #306.
This works fine. But I am not sure there won't be a race condition in the dispatching of states.

[Review on Reviewable](https://reviewable.io/reviews/bnjbvr/kresus/307)

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thanks! Just one detail I think would be nice. Please don't forget to rebase and we'll be good to merge :)

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/store.js, line 430 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/307#-K76tlNl5gtKT_tQzbHx:-K76tlNl5gtKT_tQzbHy:-66543356) ([raw file](https://github.com/bnjbvr/kresus/blob/28cea4b76ff48e2bd7d7770732dd6612e0fd0da3/client/store.js#L430)):*
This entire condition could be moved just after the `banks.account.delete(accountId);`, so that reactions to deletion are grouped in a single place. With this change, the `let` statement can stay in the `for` loop.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/307#-:-K76u6Gzz0Hi-d3QgBYD:1579724436)*

**Comment by ZeHiro** [comment]
Review status: 0 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/store.js, line 430 \[r2\]](https://reviewable.io:443/reviews/bnjbvr/kresus/307#-K76tlNl5gtKT_tQzbHx:-K77x_7kaT0NovpGmNYn:676635175) ([raw file](https://github.com/bnjbvr/kresus/blob/28cea4b76ff48e2bd7d7770732dd6612e0fd0da3/client/store.js#L430)):*
Done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/307)*

**Comment by ZeHiro** [comment]
@bnjbvr gott to merge.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/307#-:-K788E6QLWQsNSaK08Zj:598709864)*

**Comment by bnjbvr** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/bnjbvr/kresus/307)*

**Pull request merged**
