### PR TITLE
PFM ≠ Kresus.

### PR DESCRIPTION
**Pull request by jankeromnes**
`s/PFM/Kresus/g`

### CODE REVIEW

**Comment by bnjbvr** [comment]
Nice! That's something I've been willing to do for a while.

Can you also change all other references in the code, please?
https://github.com/bnjbvr/kresus/blob/master/server/lib/weboob-manager.coffee#L144
https://github.com/bnjbvr/kresus/blob/master/server/lib/report-manager.coffee#L104-L105

**Comment by ZeHiro** [comment]
Does this fix the "notification" text"? : 

PFM: 3 new transaction(s) imported.

**Comment by bnjbvr** [comment]
This will, when/if Janx fixes nits from my comment :) @jankeromnes, are you willing to do it yourself, or should i merge your commit as is and do it by myself? No pressure, it's really as you prefer :)

**Comment by ZeHiro** [comment]
OK, then it's a not opend bug.

**Pull request merged**
