### PR TITLE
Improve selection of type/categories

### PR DESCRIPTION
**Pull request by ZeHiro**
I also "switch to static mode" on change in select to avoid a second click to go back so static mode.

### CODE REVIEW

**Comment by bnjbvr** [comment]
Nice, I very much like it! Thank you for the PR!

**Comment by bnjbvr** [comment]
Can you rebase onto `incoming`, please, to avoid a merge commit?

**Comment by ZeHiro** [comment]
I do this tonight

**Comment by bnjbvr** [comment]
Perfect, thank you! I'll merge it as soon as I get it.

**Pull request closed without merging**
