### PR TITLE
adding npm to install with make install-debian

### PR DESCRIPTION
**Pull request by dattaz**

### CODE REVIEW

**Comment by bnjbvr** [comment]
Thank you for the PR! Isn't `npm` bundled with `node`  nowadays? Which version of Debian are you using?

**Comment by dattaz** [comment]
I don't think, I don't see any depends to npm with nodejs package in debian. But npm depends on nodejs
debian 8.2

**Comment by bnjbvr** [comment]
OK. Note that the development branch is `incoming`, and there are merge conflicts with this PR when I try to apply it onto `incoming`. Can you rebase your PR, please? Or just open a new one applying onto `incoming`?

**Comment by dattaz** [comment]
Done see #250

**Pull request closed without merging**
