### PR TITLE
user can add an iban to a bank

### PR DESCRIPTION
**Pull request by cylwin**
Hi @bnjbvr,
This is my code to add the iban field to the bank settings modal.

### CODE REVIEW

**Comment by ZeHiro** [comment]
Hi @cylvain there is a function in weboob to do this

**Comment by cylwin** [comment]
@ZeHiro I search a lot for this function in weboob and I didn't find anything. You have a piece of documentation for that ?

**Comment by ZeHiro** [comment]
@cylwin i found this : 
http://dev.weboob.org/api/capabilities/bank.html?highlight=bank#weboob.capabilities.bank

The paramter ban.

**Comment by cylwin** [comment]
Thank you so much @ZeHiro. I will make an other PR adding this weboob field.

**Comment by ZeHiro** [comment]
@cylwin check if it also includes the bank part of iban and key, because it could only deliver th account number (if you check in your db the account number is already here, so this could mean @bnjbvr amready uses it)

**Comment by cylwin** [comment]
@ZeHiro I just tried before answering, and it's ok. It's not the "ban" field but a "iban" field.

**Comment by cylwin** [comment]
I close this PR. I opened one here https://github.com/bnjbvr/kresus/pull/165

**Pull request closed without merging**
